#! /sbin/sh
#
# Coventry - Monitor and re-nice TS queue processes.
#
# Note: killall is available on SGI, but not on Solaris
#
IS_ON=/etc/chkconfig
COVENTRY=/usr/local/sbin
COVENTRYD=$COVENTRY/coventryd
PATH=$COVENTRY:$PATH

if $IS_ON verbose 
then
    ECHO=echo
else
    ECHO=:
fi

case $1 in
	'start')
            if $IS_ON coventry && test -x $COVENTRYD; then
	        killall -k 1 coventryd
	        $ECHO Starting coventry daemon
	        $COVENTRYD &
	    fi
	;;
	'stop')
	    $ECHO Stopping coventry daemon.
	    killall -k 1 coventryd
	;;
	*)
            echo "usage: $0 {start|stop}"

esac
