#!/usr/local/bin/perl
#see sys/resource.h
$PRIO_MIN = -20;
$PRIO_MAX =  20;
$PRIO_PROCESS = 0;
$PRIO_PGRP    = 1;
$PRIO_USER    = 2;

$NICE_OFF =  -$PRIO_MIN;
$NICE_MAX =  $PRIO_MAX + $NICE_OFF;

#see sys/param.h
$MAXPID   =  30000;

$#ARGV >= 0 or die "Usage:\n\t$0 processid [processid ... ]";

for ($i = 0; $i <= $#ARGV; $i++) {
    $pid = $ARGV[$i];
    $pid > 0 and $pid <= $MAXPID or die "processid out of range 1..$MAXPID";
    $nice = getpriority($PRIO_PROCESS, $pid) + $NICE_OFF;
    print "nice($pid) = $nice\n";
}
