#! /bin/sh
#
#  This module is part of EFCP.
#
#     Copyright 2007 William Silverman
#     Weizmann Institute of Science, Rehovot, Israel
#
#  EFCP is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  EFCP is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with EFCP; if not, write to:
#
#       Free Software Foundation, Inc.
#       59 Temple Place, Suite 330
#       Boston, MA 02111-1307  USA
#
#
# Make a prototype Logix system.
#

rm -rf ~/EFCP
mkdir ~/EFCP
mkdir ~/EFCP/Efcp-release

pushd ~/EFCP/Efcp-release

cvs -z6 -d:pserver:anonymous@cvs.savannah.nongnu.org:/sources/efcp -Q co bin

cvs -z3 -d:pserver:anonymous@cvs.savannah.nongnu.org:/sources/efcp -Q co Logix

mv Logix/*_constants.cp .
mv Logix/system/spi_constants.cp .
mv Logix/system/transform/biospi/bio_constants.cp .

rm -f Logix/*.cp
rm -f LOGIX/*/*.cp
rm -f Logix/*/*/*.cp
rm -f Logix/*/*/*/*.cp
rm -f Logix/*/*/*/*/*.cp
rm -f Logix/*/*/*/*/*/*.cp
rm -f Logix/*/*/*/*/*/*/*.cp

mv spi_constants.cp Logix/system
mv bio_constants.cp Logix/system/transform/biospi
mv *_constants.cp Logix

cd ..

tar -zcf - Efcp-release > efcp-release.tar.gz

popd

